# Задача 2

In [1]:
import numpy as np

In [2]:
N = 2
chain_len = 4
Pi = np.zeros(N + 1, )
Pi[1] = 0.8
Pi[2] = 0.2
b = np.zeros((N + 1, chain_len))
b[1][1] = 0.2
b[1][2] = 0.4
b[1][3] = 0.4
b[2][1] = 0.5
b[2][2] = 0.4
b[2][3] = 0.1
O = np.zeros(chain_len + 1, dtype ='int')
O[1] = 1
O[2] = 3
O[3] = 3
O[4] = 2
a = np.zeros((N + 1, N + 1))
a[1][1] = 0.6
a[1][2] = 0.4
a[2][1] = 0.5
a[2][2] = 0.5

In [3]:
a

array([[0. , 0. , 0. ],
       [0. , 0.6, 0.4],
       [0. , 0.5, 0.5]])

In [4]:
b

array([[0. , 0. , 0. , 0. ],
       [0. , 0.2, 0.4, 0.4],
       [0. , 0.5, 0.4, 0.1]])

In [5]:
O

array([0, 1, 3, 3, 2])

In [6]:
alpha = np.zeros((chain_len + 1, N + 1))

In [7]:
for i in range(1, N + 1):
    alpha[1][i] = Pi[i]*b[i][O[1]]

In [8]:
alpha

array([[0.  , 0.  , 0.  ],
       [0.  , 0.16, 0.1 ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [9]:
for t in range(1, chain_len):
    for j in range(1, N + 1):
        hold = 0
        for i in range(1, N + 1):
            hold = hold  + alpha[t][i] * a[i][j]
        hold = hold*b[j][O[t+1]]
        alpha[t+1][j] = hold

In [10]:
alpha

array([[0.        , 0.        , 0.        ],
       [0.        , 0.16      , 0.1       ],
       [0.        , 0.0584    , 0.0114    ],
       [0.        , 0.016296  , 0.002906  ],
       [0.        , 0.00449224, 0.00318856]])

In [11]:
alpha[chain_len].sum()

0.007680800000000001

Ответ: 0.00768